### ISSUE TITLE
swagger_ui_formatter installation problem

### ISSUE THREAD

**Issue by inbalj** [Pronovix/swagger_ui_formatter#77]
I tried to install (manually) Swagger UI Field Formatter v. 8.x-3.3 (including the JS library Swagger UI v3.52.5) on D9 and couldn't finish the installation ( I got the white screen of death....) 

<img src="https://user-images.githubusercontent.com/8232597/139249957-4ee98ae3-f518-46e8-ac51-571fe36de892.jpeg" width="60%" height="50%">

if I look at the log this is what I got:
<img src="https://user-images.githubusercontent.com/8232597/139251891-78a6411f-777f-45c8-97fb-75c68295cff9.jpeg" width="60%" height="50%">
I actually tried it in 8.x-3.2 and thought that if I upgrade it will fix the problem but to no avail.

**Comment by mxr576** [comment]
Is my assumption correct that you downloaded the tar.gz archive of this module instead of using Composer to install it? That could explain how this could happen and why we do not experience this issue by using Composer.

It seems we do not support tar.gz installs and do not plan to do that, sorry.


https://www.hojtsy.hu/blog/2021-oct-26/seven-days-go-until-drupal-8-eol-start-using-composer

**Comment by inbalj** [comment]
Unfortunately, I can't use composer to install modules on my environment due to security issues. 
The only way I can is via archives such as tar.gz. 
Is there a way to install it without using composer? maybe via drush?

**Comment by mxr576** [comment]
TBH, I do not know, in 2o22, I cannot imagine how to develop Drupal without Composer.

Although, if you can download tar.gz-s on some system/network, I guess you can also run Composer on the same place and deploy/copy Drupal codebases (artifacts) to that isolated environment that has limited access due to security reasons.

Sorry, I am closing this issue if you do not mind, because working with Drupal without Composer is really not the scope of this module. You can also ask around on Drupal Slack. For now, this is all I could say.

**Comment by inbalj** [comment]
Thank you for your reply.
